//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_Job_team
    {
        public int id { get; set; }
        public int jo_id { get; set; }
        public Nullable<int> job_team { get; set; }
    }
}
