//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_Company
    {
        public string billing_group_name { get; set; }
        public string business_number { get; set; }
        public string careersite_url { get; set; }
        public string company_name { get; set; }
        public string company_number { get; set; }
        public Nullable<int> contact_in_company { get; set; }
        public Nullable<int> creator_id { get; set; }
        public Nullable<int> employees_number { get; set; }
        public string external_id { get; set; }
        public string facebook_url { get; set; }
        public string fax { get; set; }
        public string general_PO_number { get; set; }
        public string head_quarter { get; set; }
        public int id { get; set; }
        public string linkedin_url { get; set; }
        public string note { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public string rss_urls { get; set; }
        public string switch_board { get; set; }
        public Nullable<bool> tax_exempt { get; set; }
        public string trading_name { get; set; }
        public string website { get; set; }
        public Nullable<System.DateTime> updated_timestamp { get; set; }
        public string stage { get; set; }
        public string stage_status { get; set; }
        public Nullable<int> status_id { get; set; }
    }
}
