//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_Job
    {
        public string summary { get; set; }
        public int id { get; set; }
        public string external_id { get; set; }
        public string job_title { get; set; }
        public string job_type { get; set; }
        public string category { get; set; }
        public string employment_type { get; set; }
        public Nullable<int> head_count { get; set; }
        public Nullable<System.DateTime> open_date { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public Nullable<System.DateTime> published_date { get; set; }
        public string public_description { get; set; }
        public string internal_description { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string note { get; set; }
        public Nullable<int> industry_id { get; set; }
        public Nullable<System.DateTime> hot_end_date { get; set; }
        public Nullable<int> company_location_id { get; set; }
        public Nullable<bool> floated_job { get; set; }
        public Nullable<bool> auto_submit_candidate { get; set; }
        public Nullable<bool> visible_to_all { get; set; }
        public Nullable<int> sourcing_difficulty { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public Nullable<System.DateTime> indeed_published_date { get; set; }
        public Nullable<System.DateTime> updated_timestamp { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public Nullable<int> creator_id { get; set; }
        public Nullable<decimal> percentage_placement { get; set; }
        public Nullable<decimal> forecast_annual_fee { get; set; }
        public string forecast_annual_fee_currency { get; set; }
        public Nullable<System.DateTime> projected_placement_date { get; set; }
        public Nullable<int> difficulty_level { get; set; }
        public string reason_for_difficulty { get; set; }
        public string hiring_line_manager { get; set; }
        public Nullable<int> internal_recruiter_contact_id { get; set; }
        public Nullable<int> site_manager_contact_id { get; set; }
        public string skill_keywords { get; set; }
        public Nullable<bool> private_job { get; set; }
        public string live_list_url { get; set; }
        public string max_stage { get; set; }
        public Nullable<int> active_candidate_count { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<bool> from_job_lead_converted { get; set; }
        public Nullable<int> deal_id { get; set; }
    }
}
