//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIN_Candidate
    {
        public string affiliations { get; set; }
        public string availability { get; set; }
        public Nullable<System.DateTime> availability_start { get; set; }
        public Nullable<int> candidate_source_id { get; set; }
        public string candidate_source_name { get; set; }
        public string job_title { get; set; }
        public Nullable<int> company_count { get; set; }
        public string company_name { get; set; }
        public string company_number { get; set; }
        public string contract_interval { get; set; }
        public Nullable<decimal> contract_rate { get; set; }
        public string country_of_domicile { get; set; }
        public Nullable<int> creator_id { get; set; }
        public string currency_type { get; set; }
        public Nullable<decimal> current_bonus { get; set; }
        public Nullable<decimal> current_salary { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<decimal> desired_bonus { get; set; }
        public Nullable<decimal> desired_contract_rate { get; set; }
        public Nullable<decimal> desired_salary { get; set; }
        public Nullable<decimal> desired_salary_monthly { get; set; }
        public string driving_license_number { get; set; }
        public string driving_license_type { get; set; }
        public string education_summary { get; set; }
        public string email { get; set; }
        public string employment_type { get; set; }
        public string experience { get; set; }
        public string external_id { get; set; }
        public string emergency_name { get; set; }
        public string emergency_phone { get; set; }
        public string emergency_relationship { get; set; }
        public string emergency_email { get; set; }
        public string facebook { get; set; }
        public string first_name { get; set; }
        public string first_name_kana { get; set; }
        public string gender { get; set; }
        public string gender_title { get; set; }
        public string highest_job_application_stage { get; set; }
        public string home_phone { get; set; }
        public int id { get; set; }
        public Nullable<int> ielts_score { get; set; }
        public string keyword { get; set; }
        public string last_name { get; set; }
        public string last_name_kana { get; set; }
        public Nullable<int> linked_contact_id { get; set; }
        public string linked_in { get; set; }
        public string marital_status { get; set; }
        public string met_status { get; set; }
        public string middle_name { get; set; }
        public string middle_name_kana { get; set; }
        public string mobile { get; set; }
        public string nationality { get; set; }
        public string nearest_train_station { get; set; }
        public string note { get; set; }
        public Nullable<int> note_by { get; set; }
        public Nullable<System.DateTime> note_on { get; set; }
        public Nullable<int> notice_days { get; set; }
        public string objective { get; set; }
        public string other_benefits { get; set; }
        public string payment_type { get; set; }
        public string payslip_email { get; set; }
        public string passport_no { get; set; }
        public string personal_statements { get; set; }
        public string phone { get; set; }
        public string photo_url { get; set; }
        public string place_of_birth { get; set; }
        public string preferred_language { get; set; }
        public Nullable<decimal> present_salary_rate { get; set; }
        public string publications { get; set; }
        public string reference { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public Nullable<bool> relocate { get; set; }
        public Nullable<int> salary_months_per_year { get; set; }
        public string salary_type { get; set; }
        public string skills { get; set; }
        public string statements { get; set; }
        public string summary { get; set; }
        public Nullable<int> toeic_score { get; set; }
        public Nullable<int> total_gross { get; set; }
        public string twitter { get; set; }
        public string variant { get; set; }
        public string visa_note { get; set; }
        public string visa_number { get; set; }
        public Nullable<System.DateTime> visa_renewal_date { get; set; }
        public string visa_status { get; set; }
        public string visa_type { get; set; }
        public string website { get; set; }
        public string work_email { get; set; }
        public string work_phone { get; set; }
        public string xing { get; set; }
        public Nullable<System.DateTime> updated_timestamp { get; set; }
        public string nickname { get; set; }
        public Nullable<bool> email_subscribed { get; set; }
        public Nullable<int> status_id { get; set; }
        public string candidate_company_email { get; set; }
        public string candidate_representative_name { get; set; }
        public string company_bank_name { get; set; }
        public string company_bank_branch { get; set; }
        public string company_bank_account_number { get; set; }
        public string company_bank_account_name { get; set; }
        public string company_bank_account_swift_code { get; set; }
        public string company_bank_sort_code { get; set; }
        public string company_bsb_number { get; set; }
        public Nullable<int> company_default_sale_tax_id { get; set; }
        public string company_default_sale_tax_rate { get; set; }
        public string company_default_sale_tax_number { get; set; }
        public Nullable<int> company_sale_tax_registered { get; set; }
        public Nullable<int> candidate_company_default_payment_terms { get; set; }
        public Nullable<int> umbrella_company_id { get; set; }
        public string availability_url { get; set; }
        public Nullable<System.DateTime> archived_timestamp { get; set; }
        public string archived_reason { get; set; }
        public Nullable<int> archived_by { get; set; }
        public Nullable<bool> cv_exists { get; set; }
        public Nullable<System.DateTime> cv_expiry_date { get; set; }
        public Nullable<System.DateTime> last_activity_date { get; set; }
    }
}
