//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_Candidate_education
    {
        public int id { get; set; }
        public Nullable<int> candidate_id { get; set; }
        public string course { get; set; }
        public string degree_name { get; set; }
        public string department { get; set; }
        public string description { get; set; }
        public string education_level { get; set; }
        public string gpa { get; set; }
        public string grade { get; set; }
        public string graduation_date { get; set; }
        public string honorific { get; set; }
        public string honors { get; set; }
        public string institution_address { get; set; }
        public string institution_name { get; set; }
        public string major { get; set; }
        public string minor { get; set; }
        public string qualification { get; set; }
        public string school_name { get; set; }
        public string school_address { get; set; }
        public string start_date { get; set; }
        public string thesis { get; set; }
        public string training { get; set; }
        public string school_logo { get; set; }
    }
}
