//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_candidate_current_address
    {
        public int id { get; set; }
        public int candidate_current_address_id { get; set; }
        public int candidate_id { get; set; }
        public string location_name { get; set; }
        public string address { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string district_suburb { get; set; }
        public string town_city { get; set; }
        public string zip_postal_code { get; set; }
        public string country { get; set; }
        public string state { get; set; }
        public string nearest_train_stn { get; set; }
        public string types { get; set; }
        public string phone_number { get; set; }
        public string note { get; set; }
    }
}
