//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_Candidate_document
    {
        public int id { get; set; }
        public int candidate_id { get; set; }
        public Nullable<int> document_type_id { get; set; }
        public string external_id { get; set; }
        public string file_name { get; set; }
        public Nullable<bool> original_cv { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> uploaded_date { get; set; }
        public Nullable<int> compliance_status_id { get; set; }
        public Nullable<int> compliance_condition_id { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public Nullable<System.DateTime> issued_date { get; set; }
    }
}
