//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_Company_location
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public string address { get; set; }
        public string district { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string location_name { get; set; }
        public string address_line1 { get; set; }
        public string address_line2 { get; set; }
        public string post_code { get; set; }
        public string country_code { get; set; }
        public string country { get; set; }
        public string nearest_train_station { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public string location_types { get; set; }
        public string billing_group_name { get; set; }
        public string trading_name { get; set; }
        public string general_po_number { get; set; }
        public Nullable<bool> tax_exempt { get; set; }
        public string company_number { get; set; }
        public string company_payment_term { get; set; }
        public Nullable<bool> primary_billing_address { get; set; }
        public string billing_account_code { get; set; }
    }
}
