//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetVincere.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_Candidate_work_experience
    {
        public int id { get; set; }
        public int candidate_id { get; set; }
        public string address { get; set; }
        public string company_name { get; set; }
        public Nullable<bool> current_employer { get; set; }
        public string experience_in_company { get; set; }
        public Nullable<int> functional_expertise_id { get; set; }
        public Nullable<int> industry_id { get; set; }
        public Nullable<int> sub_industry_id { get; set; }
        public string job_title { get; set; }
        public Nullable<int> sub_function_id { get; set; }
        public Nullable<System.DateTime> work_from { get; set; }
        public Nullable<System.DateTime> work_to { get; set; }
        public string company_logo { get; set; }
    }
}
